name: Node.js CI

on:
  push:
    paths:
      - "Project Code/**"
  pull_request:
    paths:
      - "Project Code/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'
      - run: 'cd "Project Code"'
      - run: npm install
      - run: npm test
        env:
          CI: true

